[package]
name = "yabir"
version = "0.1.0"
authors = ["Petr Zemek <s3rvac@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/s3rvac/yabir"
description = "Yet Another Brainfuck Interpreter in Rust"
